# Generated by Django 3.2.9 on 2023-09-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_sponsoredjobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
